set-option -ga terminal-overrides ",xterm-256color:Tc" # enable truecolor
set -g mouse on

# change leader to CTRL+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload tmux config with <leader>-r
bind r source-file ~/.config/tmux/tmux.conf

#######################################################################
### These are taken from https://github.com/tmux-plugins/tmux-sensible
#######################################################################
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

#######################################################################
# status and styles
#######################################################################
set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-right-length 50
set -g status-right "[ #S ]"
set -g status-left " "
# set -g status-style fg="#1e1e2e",bg="#a6e3a1" 
set -g window-status-current-style "bold"
set -g window-status-current-format "#W" 
# set -g window-status-style "fg=#45475a"
set -g window-status-format "#W"
# set -g message-style fg="#1e1e2e",bg="#fab387"
# set -g mode-style fg="#1e1e2e",bg="#89b4fa"

