map ctrl+shift+, set_tab_title

map ctrl+shift+enter new_window_with_cwd

map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

map ctrl+shift+m move_window_to_top
map ctrl+shift+c close_window_with_confirmation

map ctrl+shift+r start_resizing_window

map ctrl+shift+f7 focus_visible_window
map ctrl+shift+f8 swap_with_window

map ctrl+shift+a goto_layout stack
map ctrl+shift+s goto_layout tall
map ctrl+shift+d goto_layout fat

